SUBMITTED BY ---

SAURABH MEHRA (23EC65R06)
ANSHU PAL (23EC65R04)

In [ ]:
!mkdir data
!unzip dataset.zip -d ./data/

Archive:  dataset.zip
  inflating: ./data/z-dimension.csv  
  inflating: ./data/c7.png           
  inflating: ./data/c8.png           
  inflating: ./data/c9.png           
  inflating: ./data/c6.png           
  inflating: ./data/c3.png           
  inflating: ./data/c1.png           
  inflating: ./data/c5.png           
  inflating: ./data/c2.png           
  inflating: ./data/c4.png           


In [ ]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv("./data/z-dimension.csv")
df.head()

Image Name  Z-Cordinates (in mm)
0         c1                   400
1         c2                   500
2         c3                   600
3         c4                   700
4         c5                   800

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Z-Cordinates (in mm)'].plot(kind='hist', bins=20, title='Z-Cordinates (in mm)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Image Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='Z-Cordinates (in mm)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Image Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Image Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Z-Cordinates (in mm)']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Z-Cordinates (in mm)'}, axis=1)
              .sort_values('Z-Cordinates (in mm)', ascending=True))
  xs = counted['Z-Cordinates (in mm)']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('Z-Cordinates (in mm)', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Image Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Image Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Z-Cordinates (in mm)')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_6['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['Z-Cordinates (in mm)'].plot(kind='line', figsize=(8, 4), title='Z-Cordinates (in mm)')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_8['Image Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_8, x='index', y='Image Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_9['Image Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_9, x='Z-Cordinates (in mm)', y='Image Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
img_names = df["Image Name"]
Z_vals = df["Z-Cordinates (in mm)"]

In [ ]:
# Corner Detections
def filter_corners(corner_set, corner):

  return all([((corner[0] - c[0])**2)+((corner[1] - c[1])**2) > 25  for c in corner_set])


def detect_corners(img, debug = False):
  kernel = np.array([[1,1,-1,-1],
                     [1,1,-1,-1],
                     [-1,-1,1,1],
                     [-1,-1,1,1]])
  threshold = 200
  h, w = img.shape[:2]
  corners = []

  filtered_img = cv.filter2D(img, -1, kernel)
  inverted_img = 255 - img
  filtered_img2 = cv.filter2D(inverted_img, -1, kernel)

  corner_only_img = (filtered_img + filtered_img2)
  # print(min(corner_only_img.flatten()))
  if debug:
    plt.imshow(corner_only_img)
    plt.show()


  # Assuming there will not be any corner pixel on the outer pixels
  for i in range(1, h-1):
    for j in range(1, w-1):
      pix_val = corner_only_img[i,j]
      if pix_val > threshold:
        if filter_corners(corners, (i,j)):
          corners.append((i,j))

  return corners

In [ ]:
def get_world_cords(dim, unit_box = 25):
  h, w = dim

  points = []
  for i in range(h):
    for j in range(w):
      points.append((i*unit_box, j*unit_box))
  return points


In [ ]:
debug = True

for i in range(len(img_names)):
  img = cv.imread("./data/"+img_names[i]+".png")
  gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
  Z = Z_vals[i]

  corners = detect_corners(gray_img)
  # print(len(corners))
  world_cords = get_world_cords((8,11))

  A = []
  for corner_index in range(len(corners)):
    # print(corner_index)
    u,v = corners[corner_index]
    X, Y = world_cords[corner_index]

    A.append([X, Y, Z, 1, 0, 0, 0, 0, -u*X, -u*Y, -u*Z, -u])
    A.append([0, 0, 0, 0, X, Y, Y, 1, -v*X, -v*Y, -v*Z, -v])

  A = np.array(A)

  ATA = np.matmul(A.T, A)
  # print(ATA.shape)
  eigenvalues, VT = np.linalg.eig(ATA)

  # print(eigenvalues.shape, VT.shape)

  # last_col of VT
  # last row of V
  m = VT.T[-1]
  # print("m",m)

  M = m.reshape((3,4))
  print("M", M)

  print(m)



  #



M [[ 2.11310047e-16 -1.44220673e-16 -3.39762295e-08  1.35904918e-05]
 [ 6.36293681e-18  7.07106778e-01 -7.07106778e-01 -1.41377291e-15]
 [-7.81455322e-19  7.30255747e-20  2.48192143e-07 -9.92768572e-05]]
[ 2.11310047e-16 -1.44220673e-16 -3.39762295e-08  1.35904918e-05
  6.36293681e-18  7.07106778e-01 -7.07106778e-01 -1.41377291e-15
 -7.81455322e-19  7.30255747e-20  2.48192143e-07 -9.92768572e-05]
M [[ 9.34767412e-17 -1.81882507e-15  1.06135228e-07 -5.30676137e-05]
 [-8.55845450e-16 -7.07106779e-01  7.07106779e-01  2.87616530e-13]
 [-7.35646163e-19 -2.96322282e-18 -1.05762567e-07  5.28812835e-05]]
[ 9.34767412e-17 -1.81882507e-15  1.06135228e-07 -5.30676137e-05
 -8.55845450e-16 -7.07106779e-01  7.07106779e-01  2.87616530e-13
 -7.35646163e-19 -2.96322282e-18 -1.05762567e-07  5.28812835e-05]
M [[ 2.22391306e-15 -9.10960661e-15  2.32835017e-07 -1.39701009e-04]
 [-8.73799886e-16  7.07106761e-01 -7.07106761e-01  1.16488334e-12]
 [-2.49822972e-18 -1.63449159e-17  3.25275500e-07 -1.95165300e-0